service: art-intelligence
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  memorySize: 1024
  timeout: 30
  stage: dev
  region: us-west-2

custom:
  prune:
    automatic: true
    number: 10
  pythonRequirements:
    slim: true
    nodeploy:
      - boto3
      - botocore
    useDownloadCache: true
    useStaticCache: true
    dockerizePip: non-linux

package:
  individually: true
  patterns:
    - "!.DS_Store"
    - "!__pycache__/**"
    - "!node_modules/**"
    - "!tests/**"
    - "!venv"
    - "!versions/**"

functions:
  api:
    handler: api.handler
    layers:
      - ${cf:moses-common-${sls:stage}.LayerExport}
  generator:
    handler: generator.handler
    timeout: 180
    layers:
      - ${cf:moses-common-${sls:stage}.LayerExport}

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-python-requirements

